"""
🤖 AI Daily Reporter (Gemini)

Automatically enriches today's Daily Note with AI-generated summaries,
insights, and suggestions using Google's Gemini API.

Usage:
  python ai_reporter.py                # Enrich today's daily note
  python ai_reporter.py --enrich-daily # Same as above
"""

import json
import sys
from datetime import datetime
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parent
VAULT_DIR = SCRIPTS_DIR.parent
DAILY_DIR = VAULT_DIR / "Daily"
CONFIG_PATH = SCRIPTS_DIR / "config.json"


def load_config():
    if CONFIG_PATH.exists():
        return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    return {}


def get_daily_content(date=None):
    """Read today's daily note"""
    if date is None:
        date = datetime.now()
    daily_path = DAILY_DIR / f"{date.strftime('%Y-%m-%d')}.md"
    if daily_path.exists():
        return daily_path.read_text(encoding="utf-8"), daily_path
    return None, None


def enrich_daily(date=None):
    """Enrich today's Daily Note with AI insights"""
    config = load_config()
    api_key = config.get("gemini_api_key", "")
    model_name = config.get("gemini_model", "gemini-2.0-flash")
    
    if not api_key:
        print("  ⚠️ Gemini API key not configured in config.json")
        return False
    
    content, daily_path = get_daily_content(date)
    if not content:
        print("  ⚠️ Today's Daily Note not found")
        return False
    
    # Check if already enriched
    if "## 🤖 AI Summary" in content:
        print("  📋 Already enriched today")
        return True
    
    # Check if there's meaningful content
    lines = [l.strip() for l in content.split("\n") if l.strip() and not l.strip().startswith("#") and not l.strip().startswith("---") and not l.strip().startswith(">")]
    if len(lines) < 3:
        print("  ⏭️ Not enough content to enrich")
        return False
    
    try:
        import google.generativeai as genai
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel(model_name)
        
        prompt = f"""You are an AI assistant helping to summarize and enrich an Obsidian daily work log.
Analyze the following daily note and generate:
1. A brief summary (2-3 sentences) of today's work
2. Key accomplishments (bullet points)
3. Potential improvements or suggestions

Respond in the same language as the daily note. Keep it concise.
Format your response in Markdown.

Daily Note:
---
{content}
---"""
        
        response = model.generate_content(prompt)
        ai_section = f"\n\n## 🤖 AI Summary\n\n> Generated by {model_name} at {datetime.now().strftime('%H:%M')}\n\n{response.text}\n"
        
        # Append AI section to daily note
        updated_content = content.rstrip() + ai_section
        daily_path.write_text(updated_content, encoding="utf-8")
        
        print(f"  ✅ Daily Note enriched with {model_name}")
        return True
        
    except ImportError:
        print("  ⚠️ google-generativeai not installed: pip install google-generativeai")
        return False
    except Exception as e:
        print(f"  ⚠️ AI enrichment failed: {e}")
        return False


def main():
    enrich_daily()


if __name__ == "__main__":
    main()
